name: Modify HDI Files and Upload to Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  modify-hdi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Required Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mtools lzma fuse3 libfuse2 libguestfs-tools zip

      - name: Extract HDI File
        run: |
          mkdir extracted_hdi
          unzip fd98_hd_250m_20220123.zip -d extracted_hdi

      - name: Process HDI Files
        run: |
          mkdir modified_hdi temp_mount
          for hdi in extracted_hdi/*.hdi; do
            hdi_name=$(basename "$hdi")
            # Attempt to mount using guestmount (libguestfs)
            # Ensure the proper device is mounted (this could change depending on the actual HDI format)
            sudo guestmount -a "$hdi" -m /dev/sda --ro temp_mount || echo "Failed to mount $hdi"
            # If mount is successful, copy files and unmount
            if mountpoint -q temp_mount; then
              sudo cp -v *.XDF *.EXE temp_mount/
              sudo guestunmount temp_mount || echo "Failed to unmount $hdi"
            else
              echo "Skipping $hdi due to mount failure."
            fi
            cp "$hdi" "modified_hdi/$hdi_name"
          done

      - name: Compress Modified HDI File with Zip
        run: |
          # Create a zip archive with maximum compression (-9)
          for hdi in modified_hdi/*.hdi; do
            zip -9 "${hdi}.zip" "$hdi"
          done

      - name: Commit and Push Changes to Repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          # Make sure we are on the correct branch (main)
          git checkout main
          # Pull remote changes to avoid conflicts
          git pull --rebase origin main
          # Create a directory to store the modified HDI files
          mkdir -p extracted_hdi/modified
          mv modified_hdi/*.hdi.zip extracted_hdi/modified/
          # Stage and commit the changes
          git add extracted_hdi/modified/*.hdi.zip
          git commit -m "Updated HDI files with XDF and EXE files and compressed them"
          # Push to the repository (without using releases)
          git push origin main
