name: Modify HDI Files and Upload to Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  modify-hdi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Required Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mtools lzma fuse3 libfuse2

      - name: Extract HDI File
        run: |
          mkdir extracted_hdi
          unzip fd98_hd_250m_20220123.zip -d extracted_hdi

      - name: Process HDI Files
        run: |
          mkdir modified_hdi temp_mount
          for hdi in extracted_hdi/*.hdi; do
            hdi_name=$(basename "$hdi")
            # Try using fuse to mount HDI instead of standard mount
            sudo mount -t auto -o loop "$hdi" temp_mount || (echo "Mount failed for $hdi" && dmesg)
            # If mount is successful, copy files and unmount
            sudo cp -v *.XDF *.EXE temp_mount/
            sudo umount temp_mount || echo "Failed to unmount $hdi"
            cp "$hdi" "modified_hdi/$hdi_name"
          done

      - name: Compress Modified HDI File
        run: |
          xz -9 -e modified_hdi/*.hdi

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b release
          mv modified_hdi/*.hdi.xz extracted_hdi/
          git add extracted_hdi/*.hdi.xz
          git commit -m "Updated HDI files with XDF and EXE files and compressed them"
          git push origin release --force
