name: Modify HDI Files and Upload to Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  modify-hdi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Required Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mtools lzma fuse3 libfuse2 libguestfs-tools

      - name: Extract HDI File
        run: |
          mkdir extracted_hdi
          unzip fd98_hd_250m_20220123.zip -d extracted_hdi

      - name: Process HDI Files
        run: |
          mkdir modified_hdi temp_mount
          for hdi in extracted_hdi/*.hdi; do
            hdi_name=$(basename "$hdi")
            # Attempt to mount using guestmount (libguestfs)
            sudo guestmount -a "$hdi" -m /dev/sda1 --ro temp_mount || echo "Failed to mount $hdi"
            # If mount is successful, copy files and unmount
            sudo cp -v *.XDF *.EXE temp_mount/
            sudo guestunmount temp_mount || echo "Failed to unmount $hdi"
            cp "$hdi" "modified_hdi/$hdi_name"
          done

      - name: Compress Modified HDI File
        run: |
          xz -9 -e modified_hdi/*.hdi

      - name: Commit and Push Changes to Repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          # Make sure we are on the correct branch (main)
          git checkout main
          # Create a directory to store the modified HDI files
          mkdir -p extracted_hdi/modified
          mv modified_hdi/*.hdi.xz extracted_hdi/modified/
          # Stage and commit the changes
          git add extracted_hdi/modified/*.hdi.xz
          git commit -m "Updated HDI files with XDF and EXE files and compressed them"
          # Push to the repository (without using releases)
          git push origin main
