name: Modify IMG Files and Upload to Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  modify-img:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Required Tools
        run: sudo apt-get update && sudo apt-get install -y mtools

      - name: Process IMG Files
        run: |
          mkdir modified_img
          for img in img/*.img; do
            img_name=$(basename "$img")
            mcopy -i "$img" *.XDF ::
            mcopy -i "$img" *.EXE ::
            cp "$img" "modified_img/$img_name"
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b release
          mv modified_img/* img/
          git add img/*.img
          git commit -m "Updated IMG files with XDF and EXE files"
          git push origin release --force
